table cotacoes
	lineageTag: 83322f44-ca7c-4cf0-b683-2429a3fafd52

	measure 'Cotação do dia' = ```
			AVERAGE(cotacoes[Cotacao]) 
			```
		displayFolder: Medidas
		lineageTag: 8fbe0f51-f9ba-423d-a0b6-f738336f21bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: 5dff9cfc-d3e4-4ac6-8b59-2034df409424
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column DataHora
		dataType: dateTime
		formatString: General Date
		displayFolder: Colunas
		lineageTag: ebe2cfdc-8d37-403b-9dd9-5d6bcb9f3aed
		summarizeBy: none
		sourceColumn: DataHora

		variation Variation
			isDefault
			relationship: a9b5c32f-956d-48ea-a2a1-71de65fd38e0
			defaultHierarchy: LocalDateTable_0c7ee403-a2fe-4d6f-83bc-a30c1990eab3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Cotacao
		dataType: double
		displayFolder: Colunas
		lineageTag: ebda4c8e-db55-4b06-a329-074225a49f31
		summarizeBy: average
		sourceColumn: Cotacao

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TipoBoletim
		dataType: string
		displayFolder: Colunas
		lineageTag: 7ec9aa79-f5f9-41c6-90e5-f992a2046050
		summarizeBy: none
		sourceColumn: TipoBoletim

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Short Date
		displayFolder: Colunas
		lineageTag: ded7ba1c-9878-427e-95f2-552d9dbbeba8
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition cotacoes = m
		mode: import
		queryGroup: Fatos
		source = getCotacoes(data_inicial, data_final)

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

